name: hello-snap
base: core18
version: git
summary: Hello again from Golang
description: |
  hello prints a friendly greeting.
grade: devel
confinement: devmode

apps:
  hell-snap:
    command: hello-snap

parts:
  hello-snap:
    plugin: go
    go-importpath: github.com/ryumei/hello-snap
    source: .
    source-type: git
    build-packages:
      - gcc
